name: advice-on-fire

services:
    website:
        image: ghcr.io/dragoninventor/advice-on-fire/website:latest
        restart: unless-stopped
        env_file:
            - .env.local
        volumes:
            - payload-data:/app/apps/website/public
        working_dir: /app
        depends_on:
            - mongo

    mongo:
        restart: always
        image: mongo:latest
        command:
            - --storageEngine=wiredTiger
        volumes:
            - data:/data/db

    caddy:
        restart: unless-stopped
        build:
            context: ./tooling/caddy
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - website
        environment:
            - DOMAIN=adviceonfire.com

volumes:
    data:
        external: true
    payload-data:
        external: true
    caddy_data:
        name: "caddy_data"
    caddy_config:
        name: "caddy_config"

secrets:
    DOTENV_PRIVATE_KEY_PRODUCTION:
        environment: DOTENV_PRIVATE_KEY_PRODUCTION
