import { Config } from "payload";
import {
	AlignFeature,
	BlockquoteFeature,
	BoldFeature,
	ChecklistFeature,
	FixedToolbarFeature,
	HeadingFeature,
	HorizontalRuleFeature,
	IndentFeature,
	InlineCodeFeature,
	InlineToolbarFeature,
	ItalicFeature,
	lexicalEditor,
	LinkFeature,
	OrderedListFeature,
	ParagraphFeature,
	RelationshipFeature,
	StrikethroughFeature,
	SubscriptFeature,
	SuperscriptFeature,
	UnderlineFeature,
	UnorderedListFeature,
	UploadFeature,
} from "@payloadcms/richtext-lexical";

export const defaultLexical: Config["editor"] = lexicalEditor({
	features: () => {
		return [
			BoldFeature(),
			ItalicFeature(),
			UnderlineFeature(),
			StrikethroughFeature(),
			SubscriptFeature(),
			SuperscriptFeature(),
			InlineCodeFeature(),
			ParagraphFeature(),
			HeadingFeature(),
			AlignFeature(),
			IndentFeature(),
			UnorderedListFeature(),
			OrderedListFeature(),
			ChecklistFeature(),
			RelationshipFeature(),
			BlockquoteFeature(),
			UploadFeature(),
			HorizontalRuleFeature(),
			BlockquoteFeature(),
			FixedToolbarFeature(),
			InlineToolbarFeature(),
			LinkFeature(),
		];
	},
});
